/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminSetupRouteImport } from './routes/admin-setup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as SocialLoginRouteImport } from './routes/social-login'
import { Route as SocialPortalRouteImport } from './routes/social-portal'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedKdsRouteImport } from './routes/_authenticated/kds'
import { Route as AuthenticatedSalesRouteImport } from './routes/_authenticated/sales'
import { Route as ApiPublicPurgeUsersRouteImport } from './routes/api/public/purge-users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/admin-setup',
  path: '/admin-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialLoginRoute = SocialLoginRouteImport.update({
  id: '/social-login',
  path: '/social-login',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialPortalRoute = SocialPortalRouteImport.update({
  id: '/social-portal',
  path: '/social-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKdsRoute = AuthenticatedKdsRouteImport.update({
  id: '/kds',
  path: '/kds',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesRoute = AuthenticatedSalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPurgeUsersRoute = ApiPublicPurgeUsersRouteImport.update({
  id: '/api/public/purge-users',
  path: '/api/public/purge-users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-setup': typeof AdminSetupRoute
  '/auth': typeof AuthRoute
  '/social-login': typeof SocialLoginRoute
  '/social-portal': typeof SocialPortalRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/kds': typeof AuthenticatedKdsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/api/public/purge-users': typeof ApiPublicPurgeUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-setup': typeof AdminSetupRoute
  '/auth': typeof AuthRoute
  '/social-login': typeof SocialLoginRoute
  '/social-portal': typeof SocialPortalRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/kds': typeof AuthenticatedKdsRoute
  '/sales': typeof AuthenticatedSalesRoute
  '/api/public/purge-users': typeof ApiPublicPurgeUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin-setup': typeof AdminSetupRoute
  '/auth': typeof AuthRoute
  '/social-login': typeof SocialLoginRoute
  '/social-portal': typeof SocialPortalRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/kds': typeof AuthenticatedKdsRoute
  '/_authenticated/sales': typeof AuthenticatedSalesRoute
  '/api/public/purge-users': typeof ApiPublicPurgeUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-setup'
    | '/auth'
    | '/social-login'
    | '/social-portal'
    | '/admin'
    | '/kds'
    | '/sales'
    | '/api/public/purge-users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-setup'
    | '/auth'
    | '/social-login'
    | '/social-portal'
    | '/admin'
    | '/kds'
    | '/sales'
    | '/api/public/purge-users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-setup'
    | '/auth'
    | '/social-login'
    | '/social-portal'
    | '/_authenticated/admin'
    | '/_authenticated/kds'
    | '/_authenticated/sales'
    | '/api/public/purge-users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminSetupRoute: typeof AdminSetupRoute
  AuthRoute: typeof AuthRoute
  SocialLoginRoute: typeof SocialLoginRoute
  SocialPortalRoute: typeof SocialPortalRoute
  ApiPublicPurgeUsersRoute: typeof ApiPublicPurgeUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-setup': {
      id: '/admin-setup'
      path: '/admin-setup'
      fullPath: '/admin-setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-login': {
      id: '/social-login'
      path: '/social-login'
      fullPath: '/social-login'
      preLoaderRoute: typeof SocialLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-portal': {
      id: '/social-portal'
      path: '/social-portal'
      fullPath: '/social-portal'
      preLoaderRoute: typeof SocialPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/kds': {
      id: '/_authenticated/kds'
      path: '/kds'
      fullPath: '/kds'
      preLoaderRoute: typeof AuthenticatedKdsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales': {
      id: '/_authenticated/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof AuthenticatedSalesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/purge-users': {
      id: '/api/public/purge-users'
      path: '/api/public/purge-users'
      fullPath: '/api/public/purge-users'
      preLoaderRoute: typeof ApiPublicPurgeUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedKdsRoute: typeof AuthenticatedKdsRoute
  AuthenticatedSalesRoute: typeof AuthenticatedSalesRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedKdsRoute: AuthenticatedKdsRoute,
  AuthenticatedSalesRoute: AuthenticatedSalesRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminSetupRoute: AdminSetupRoute,
  AuthRoute: AuthRoute,
  SocialLoginRoute: SocialLoginRoute,
  SocialPortalRoute: SocialPortalRoute,
  ApiPublicPurgeUsersRoute: ApiPublicPurgeUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
